In [ ]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output

In [ ]:
env = gym.make('FrozenLake-v0')

INFO:gym.envs.registration:Making new env: FrozenLake-v0
[2023-05-08 12:21:13,475] Making new env: FrozenLake-v0
/usr/local/lib/python3.10/dist-packages/gym/envs/registration.py:17: PkgResourcesDeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.
  result = entry_point.load(False)


In [ ]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

q_table = np.zeros((state_space_size, action_space_size))

In [ ]:
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
num_episodes = 10000
max_steps_per_episode = 99

learning_rate = 0.01
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.001
exploration_decay_rate = 0.001

**best hyperparameter values I found till now**

num_episodes = 10000

max_steps_per_episode = 99

learning_rate = 0.01

discount_rate = 0.95

exploration_rate = 1

max_exploration_rate = 1

min_exploration_rate = 0.001

exploration_decay_rate = 0.001

In [ ]:
rewards_all_episodes = []

In [ ]:
for episode in range(num_episodes):
    state = env.reset()
    done = False
    rewards_current_episode = 0

    for step in range(max_steps_per_episode):
        # Exploration-exploitation trade-off
        exploration_rate_threshold = random.uniform(0, 1)
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state,:]) 
        else:
            action = env.action_space.sample()

        new_state, reward, done, info = env.step(action)

        q_table[state, action] = q_table[state, action] * (1 - learning_rate) + learning_rate * (reward + discount_rate * np.max(q_table[new_state, :]))

        state = new_state
        rewards_current_episode += reward 

        if done == True: 
            break

    exploration_rate = min_exploration_rate + (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate*episode)

    rewards_all_episodes.append(rewards_current_episode)

rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes),num_episodes/1000)
count = 1000
print("********Average reward per thousand episodes********\n")
for r in rewards_per_thousand_episodes:
    print(count, ": ", str(sum(r/1000)))
    count += 1000

print(q_table)

********Average reward per thousand episodes********

1000 :  0.06100000000000005
2000 :  0.21500000000000016
3000 :  0.45000000000000034
4000 :  0.6070000000000004
5000 :  0.6840000000000005
6000 :  0.7210000000000005
7000 :  0.7180000000000005
8000 :  0.6950000000000005
9000 :  0.7180000000000005
10000 :  0.7160000000000005
[[0.51573323 0.51248591 0.51253478 0.50882867]
 [0.32581034 0.2949522  0.25116099 0.44938572]
 [0.38064014 0.30787288 0.2779822  0.31810764]
 [0.13364492 0.12853141 0.09065851 0.28386851]
 [0.53034811 0.39709588 0.37277028 0.38859224]
 [0.         0.         0.         0.        ]
 [0.32387094 0.147184   0.26519134 0.11148743]
 [0.         0.         0.         0.        ]
 [0.39420382 0.39251943 0.36856982 0.57094869]
 [0.42979157 0.61996914 0.46435013 0.39731114]
 [0.59469442 0.49803726 0.36236169 0.27326158]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.46575198 0.48334617 0.71818762 0.48999714]
 [0.7107256  0

In [ ]:
for episode in range(3):
    state = env.reset()
    done = False
    print("*****EPISODE ", episode+1, "*****\n\n\n\n")
    time.sleep(0.3)

    for step in range(max_steps_per_episode):        
        clear_output(wait=True)
        print(env.render());
        time.sleep(0.3)

        action = np.argmax(q_table[state,:])        
        new_state, reward, done, info = env.step(action)

        if done:
            clear_output(wait=True)
            print(env.render());
            if reward == 1:
                print("****You reached the goal!****")
                time.sleep(3)
            else:
                print("****You fell through a hole!****")
                time.sleep(3)
                clear_output(wait=True)
            break

        state = new_state

env.close()

  (Down)
SFFF
FHFH
FFFH
HFFG
****You reached the goal!****
